// <auto-generated />
using M19_Demo_Entity_Framework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace M19_Demo_Entity_Framework.Migrations
{
    [DbContext(typeof(EFDbContext))]
    [Migration("20200828141244_init2")]
    partial class init2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("M19_Demo_Entity_Framework.Models.Transportmittel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AktuelleGeschwindigkeit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FZustand")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("MaximalGeschwindigkeit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Preis")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("DieTransportmittel");
                });
#pragma warning restore 612, 618
        }
    }
}
